'use strict';
const $=s=>document.querySelector(s);
const data=window.YINLANG_DATA||{artists:[],sources:[],metrics:[],works:[]};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=s=>{try{const u=new URL(s);return u.protocol==='https:'?u.href:null;}catch{return null;}};
const safeAsset=s=>typeof s==='string'&&/^(screenshots|assets)\/[a-zA-Z0-9_./-]+$/.test(s)&&!s.includes('..')?s:null;
let artists=[...data.artists],current='chace',view='overview',toastTimer;
try{let saved=JSON.parse(localStorage.getItem('yinlang-screenshot-artists'));if(!Array.isArray(saved)){saved=JSON.parse(localStorage.getItem('yinlang-v3'));}if(Array.isArray(saved)){for(const a of saved){if(typeof a.id==='string'&&typeof a.name==='string'&&!artists.some(x=>x.id===a.id||x.name===a.name))artists.push({id:a.id,name:a.name,publicUid:a.publicUid,publicName:a.publicName});}}}catch{}
try{const roster=JSON.parse(localStorage.getItem('yinlang-roster-v1'));if(Array.isArray(roster))artists=roster.filter(a=>a&&typeof a.id==='string'&&typeof a.name==='string').map(a=>({...data.artists.find(x=>x.id===a.id),...a}));}catch{}
if(!artists.some(a=>a.id===current))current=artists[0]?.id;
const active=()=>artists.find(a=>a.id===current);
const sourcesFor=a=>data.sources.filter(s=>s.artistId===a.id);
const sourceFor=r=>data.sources.find(s=>s.id===r.sourceId);
const metricsFor=a=>data.metrics.filter(r=>r.artistId===a.id&&r.platform!=='微博'&&sourceFor(r)?.artistId===a.id);
const dateLabel=s=>s?.kind==='web'?new Date(s.fetchedAt).toLocaleString('zh-CN',{hour12:false}):(s?.capturedAt||'日期未提供');
const sourceTime=s=>s?.kind==='web'?s.fetchedAt:(s?.capturedAt||'');
function notify(s){$('#toast').textContent=s;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',4000);}
function save(){try{localStorage.setItem('yinlang-roster-v1',JSON.stringify(artists.map(({id,name,publicUid,publicName})=>({id,name,publicUid,publicName}))));}catch{notify('浏览器未能保存艺人列表。');}}
function avatar(a,cls='avatar'){const path=safeAsset(a.photo)||safeURL(a.photo);return path?`<img class="${cls}" src="${esc(path)}" style="object-position:${esc(a.photoPosition||'50% 50%')}" alt="${esc(a.name)}来源头像" referrerpolicy="no-referrer">`:`<span class="${cls}">${esc(a.name.slice(0,1))}</span>`;}
document.addEventListener('error',e=>{if(e.target.tagName==='IMG'){const span=document.createElement('span');span.className=e.target.className;span.textContent=e.target.alt.slice(0,1)||'♪';if(e.target.className==='hero-avatar')$('#photo-note').textContent='来源头像暂时无法加载';e.target.replaceWith(span);}},true);
function empty(title,copy){return `<div class="empty"><span>◎</span><h3>${esc(title)}</h3><p>${esc(copy)}</p></div>`;}
function renderList(){const q=$('#search').value.trim().toLocaleLowerCase();$('#count').textContent=artists.length;$('#artists').innerHTML=artists.filter(a=>a.name.toLocaleLowerCase().includes(q)).map(a=>`<button class="artist ${a.id===current?'selected':''}" data-artist="${esc(a.id)}" aria-pressed="${a.id===current}">${avatar(a)}<span><b>${esc(a.name)}</b><small>${esc(a.tagline||'艺人档案')}</small></span></button>`).join('')||'<p class="help">没有匹配的艺人，可以添加新艺人。</p>';}
function render(){const a=active();renderList();
$('#delete-artist').disabled=!a;$('#refresh-public').disabled=!a||pending.has(a.id);
if(!a){$('#artist-title').textContent='添加第一位艺人';$('#artist-sub').textContent='建立你的音乐观察列表';$('#hero-photo').innerHTML='';$('#photo-note').innerHTML='';$('#connection').hidden=true;$('#notice').hidden=true;for(const id of ['metrics','music-platforms','latest-release','song-content','audience-content','source-content','event-content','overview-events'])$('#'+id).innerHTML='';showView(view);return;}
$('#artist-title').textContent=a.name;$('#artist-sub').textContent=a.tagline||'艺人看板';$('#hero-photo').innerHTML=avatar(a,'hero-avatar');$('#photo-note').innerHTML='';$('#connection').hidden=true;$('#notice').hidden=!a.publicError;$('#notice').textContent=a.publicError?'本次更新未成功，保留上次数据。':'';
const sources=sourcesFor(a),records=metricsFor(a);
// Select newest dated record for each platform/metric. Undated captures are shown separately.
const latest=new Map(),undated=[];for(const r of records){const s=sourceFor(r),key=`${r.platform}|${r.metric}`;if(!sourceTime(s)){undated.push(r);continue;}const prev=latest.get(key);if(!prev||sourceTime(s)>sourceTime(sourceFor(prev)))latest.set(key,r);}
const visible=[...latest.values(),...undated];$('#metrics').innerHTML=visible.length?visible.map(r=>{const s=sourceFor(r);return `<article class="metric"><div class="label">${esc(r.label)}</div><div class="platform">${esc(r.platform)}</div><div class="value">${esc(r.displayValue)}</div><div class="detail">${r.chartDate?`榜单日期：${esc(r.chartDate)}<br>`:""}${s.kind==='web'?'读取时间':'截图日期'}：${esc(dateLabel(s))}<br>${r.exact===false?'平台约数 · ':''}<button class="source-link" data-source="${esc(s.id)}">查看来源 ↗</button></div></article>`;}).join(''):'<p class="music-status">暂未取得可核对的音乐表现指标，先查看近期作品与活动。</p>';
renderWorks();renderAudience();renderMusicPlatforms();renderEvents();renderSources();showView(view);}
const worksFor=a=>data.works.filter(w=>w.artistId===a.id&&sourceFor(w)?.artistId===a.id).sort((a,b)=>b.date.localeCompare(a.date));
const external=(url,label)=>safeURL(url)?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`:'';
function renderWorks(){const works=worksFor(active());$('#song-content').innerHTML=works.length?works.map((w,i)=>`<article class="release"><div class="release-number">${String(i+1).padStart(2,'0')}</div><div><small>${esc(w.date)} · ${esc(w.type)}</small><h3>${esc(w.name)}</h3><p>${esc(w.details)}</p><div class="release-links">${(w.links||[]).map(l=>external(l.url,l.platform)).join('')}<button class="source-link" data-source="${esc(w.sourceId)}">发行来源 ↗</button></div></div></article>`).join(''):empty('暂未收录近期发行','核对后显示歌曲与专辑。');const first=works[0];$('#latest-release').innerHTML=first?`<div class="eyebrow">RECENT RELEASE</div><small>${esc(first.date)} · ${esc(first.type)}</small><h2>${esc(first.name)}</h2><p>${esc(first.details)}</p><button id="open-works">查看近期作品 ↗</button>`:'<h2>下一首，值得期待。</h2><p>近期发行将在这里呈现。</p>';$('#open-works')?.addEventListener('click',()=>showView('songs'));}
function renderMusicPlatforms(){const a=active(),works=worksFor(a);const platforms=[...new Set(works.flatMap(w=>(w.links||[]).map(l=>l.platform)))];$('#music-platforms').innerHTML=platforms.map(platform=>{const matches=works.filter(w=>(w.links||[]).some(l=>l.platform===platform));const home=(a.musicHome||[]).find(l=>l.platform===platform);return `<article class="platform-card"><div class="section-heading"><h2>${esc(platform)} · 作品</h2>${home?external(home.url,'艺人主页'):''}</div>${matches.slice(0,2).map(w=>`<div class="platform-work"><b>${esc(w.name)}</b><small>${esc(w.date)} · ${esc(w.type)}</small>${external(w.links.find(l=>l.platform===platform).url,'作品页面')}</div>`).join('')}</article>`;}).join('');}
function renderEvents(){const items=(data.events||[]).filter(e=>e.artistId===current);const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Taipei'}).format(new Date());const status=e=>e.status==='unannounced'?'待官宣':e.status==='ended'||e.date&&e.date<today?'已结束':'已官宣';const sorted=[...items].sort((a,b)=>(status(a)==='已结束')-(status(b)==='已结束')||(b.date||'').localeCompare(a.date||''));const card=e=>`<article class="event-card"><div class="event-top"><span class="event-city">${esc(e.city)}</span><span class="event-status ${e.status==='unannounced'?'tentative':''}">${status(e)}</span></div><h3>${esc(e.title)}</h3><p>${esc(e.date||'日期待定')} · ${esc(e.venue||'场馆待定')}</p><small>${esc(e.note||'')}</small>${e.url?external(e.url,e.sourceLabel||'活动详情'):`<span class="help">${esc(e.sourceLabel||'信息待核对')}</span>`}</article>`;$('#event-content').innerHTML=sorted.length?sorted.map(card).join(''):empty('暂无近期活动记录','已官宣的演出和待确认行程会在这里展示。');$('#overview-events').innerHTML=sorted.length?`<div class="section-heading"><h2>近期活动</h2><button class="source-link" id="all-events">查看全部 ↗</button></div><div class="event-grid">${sorted.slice(0,2).map(card).join('')}</div>`:'';$('#all-events')?.addEventListener('click',()=>showView('events'));}
function renderAudience(){const a=active(),profile=a.audience;const records=metricsFor(a);const fans=records.filter(r=>r.metric==='followers').sort((a,b)=>sourceTime(sourceFor(b)).localeCompare(sourceTime(sourceFor(a))))[0];$('#audience-content').innerHTML=profile?`<div class="audience-intro"><div class="eyebrow">AUDIENCE INSIGHTS · 分析推断</div><h2>${esc(profile.headline)}</h2><p>综合已收录的作品、发行动态与平台指标；并非平台听众抽样统计。</p><div class="audience-chips"><span>${worksFor(a).length} 项近期作品</span>${fans?`<span>微博粉丝 ${esc(fans.displayValue)} · 不等同听众人数</span>`:''}</div></div><div class="audience-grid">${profile.cards.map(c=>`<article class="box"><small>${esc(c.title)}</small><h3>${esc(c.analysis)}</h3><p>${esc(c.evidence)}</p></article>`).join('')}</div><div class="audience-foot"><span>年龄 / 性别 / 城市：暂无统计数据</span><button class="source-link" id="audience-sources">查看数据来源 ↗</button></div>`:empty('资料还不足以形成画像','收录作品与平台数据后再分析听众兴趣。');$('#audience-sources')?.addEventListener('click',()=>showView('sources'));}
function renderSources(){const a=active();const latest=new Map();for(const source of sourcesFor(a)){const key=source.url||source.id;const prev=latest.get(key);if(!prev||sourceTime(source)>sourceTime(prev))latest.set(key,source);}const homes=(a.musicHome||[]).map(l=>`<article class="source-row"><b>${esc(l.platform)}</b>${external(l.url,'艺人主页')}</article>`).join('');$('#source-content').innerHTML=homes+[...latest.values()].map(s=>`<article class="screenshot-source" id="source-${esc(s.id)}"><div class="section-heading"><h2>${esc(s.platform)} · ${esc(s.platform==='微博'?'艺人主页':s.label)}</h2>${external(s.url,'打开页面')}</div><small class="help">核对时间 ${esc(dateLabel(s))}</small>${s.note?`<details><summary>指标口径</summary><p class="help">${esc(s.note)}</p></details>`:''}</article>`).join('');if(!$('#source-content').innerHTML)$('#source-content').innerHTML=empty('暂未收录来源','艺人主页和作品页面会集中显示在这里。');}
function showView(v){view=v;document.querySelectorAll('.panel').forEach(el=>el.hidden=el.id!==v);document.querySelectorAll('[data-view]').forEach(el=>{el.classList.toggle('active',el.dataset.view===v);el.setAttribute('aria-current',el.dataset.view===v?'page':'false');});}
$('#artists').onclick=e=>{const b=e.target.closest('[data-artist]');if(b){current=b.dataset.artist;render();refreshMusic(active());}};
$('#search').oninput=renderList;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());
$('#add').onclick=()=>$('#artist-dialog').showModal();$('#manage').onclick=()=>showView('sources');$('#show-sources').onclick=()=>showView('sources');
$('#artist-form').onsubmit=e=>{e.preventDefault();const name=$('#artist-query').value.trim();if(!name)return;const f=new FormData(e.target),link=f.get('publicUrl').trim();let uid=null;if(link){try{const u=new URL(link);if(!['weibo.com','www.weibo.com','www.sina.cn','sina.cn'].includes(u.hostname))throw Error();uid=u.pathname.match(/^\/(?:u\/|media\/)?(\d{5,20})\/?$/)?.[1];if(!uid)throw Error();}catch{notify('请填写含数字 ID 的本人微博或新浪主页，暂不支持昵称网址。');return;}}const old=artists.find(a=>a.name.toLocaleLowerCase()===name.toLocaleLowerCase());if(old){current=old.id;if(uid&&old.publicUid&&old.publicUid!==uid){notify('现有档案绑定了不同来源，请先核对艺人身份。');return;}if(uid){old.publicUid=uid;old.publicName=name;}}else{const seed=data.artists.find(a=>a.name.toLocaleLowerCase()===name.toLocaleLowerCase());current=seed?.id||'artist-'+Date.now();artists.push({...seed,id:current,name,...(uid?{publicUid:uid,publicName:name}:{})});for(const p of window.YINLANG_PUBLIC?.profiles||[])if(p.artistId===current)ingestProfile(p);}save();$('#search').value='';e.target.reset();$('#artist-dialog').close();render();refreshMusic(active(),true);};
document.addEventListener('click',e=>{const b=e.target.closest('[data-source]');if(b){showView('sources');document.getElementById('source-'+b.dataset.source)?.scrollIntoView({behavior:'smooth'});}});

function ingestProfile(p,target){const a=target||artists.find(x=>x.id===p.artistId);if(!a)return;a.publicUid=p.uid;a.publicName=p.name;a.photo=safeAsset(a.localPhoto)||safeURL(p.photo);const id='web-'+p.uid+'-'+p.fetchedAt.replace(/[^0-9]/g,'');if(!data.sources.some(x=>x.id===id)){data.sources.push({id,artistId:a.id,kind:'web',platform:'微博',label:p.sourceLabel,url:p.sourceUrl,fetchedAt:p.fetchedAt,capturedAt:p.fetchedAt.slice(0,10),note:p.note});for(const r of p.metrics)data.metrics.push({...r,artistId:a.id,platform:'微博',sourceId:id});}}
const pending=new Set();
async function refreshPublic(a,explicit=false){if(!a)return;if(!a.publicUid){if(explicit)notify('当前艺人暂未设置可更新的平台来源。');return;}if(pending.has(a.id))return;pending.add(a.id);$('#refresh-public').disabled=true;try{const query=new URLSearchParams({uid:a.publicUid,id:a.id,name:a.publicName||a.name});const res=await fetch('/api/public/profile?'+query,{signal:AbortSignal.timeout(20000)});if(!res.ok)throw Error('当前为静态预览，已显示最近保存的公开资料。使用本地数据服务可检查更新。');const result=await res.json();if(result.profile){if(result.profile.uid!==a.publicUid)throw Error('返回的公开账号不一致，未更新。');ingestProfile(result.profile,a);}a.publicError=result.error||'';if(explicit)notify(result.error||(result.cached?'数据已是最近一次记录。':'数据已更新。'));}catch(e){if(explicit){a.publicError=e.message;notify(e.message);}}finally{pending.delete(a.id);$('#refresh-public').disabled=false;render();}}
for(const p of [...(window.YINLANG_PUBLIC?.history||[]),...(window.YINLANG_PUBLIC?.profiles||[])])ingestProfile(p);
function ingestMusic(payload){for(const source of payload.sources||[]){if(!data.sources.some(s=>s.id===source.id))data.sources.push(source);}for(const metric of payload.metrics||[]){if(!data.metrics.some(m=>m.sourceId===metric.sourceId&&m.metric===metric.metric&&m.artistId===metric.artistId))data.metrics.push(metric);}}
ingestMusic(window.YINLANG_MUSIC||{});
async function refreshMusic(a,explicit=false){if(!a||pending.has(a.id))return;pending.add(a.id);$('#refresh-public').disabled=true;try{const response=await fetch('/api/music',{signal:AbortSignal.timeout(25000)});if(!response.ok)throw Error('音乐数据服务暂不可用');const payload=await response.json();ingestMusic(payload);a.publicError=payload.error||'';if(explicit)notify(payload.error?'部分音乐来源未能更新，保留最近记录。':'已检查音乐来源，显示最近可核对的数据。');}catch(e){if(explicit){a.publicError=e.message;notify('未能更新音乐数据，保留最近记录。');}}finally{pending.delete(a.id);render();}}
let deleteTarget=null;
$('#delete-artist').onclick=()=>{deleteTarget=current;$('#delete-copy').textContent='将 '+active().name+' 从看板移除，之后可以通过添加艺人重新加入。';$('#delete-dialog').showModal();};
$('#confirm-delete').onclick=()=>{const removed=artists.find(a=>a.id===deleteTarget);artists=artists.filter(a=>a.id!==deleteTarget);if(current===deleteTarget)current=artists[0]?.id;save();$('#delete-dialog').close();render();notify('已删除 '+(removed?.name||'艺人'));};
$('#refresh-public').onclick=()=>refreshMusic(active(),true);
render();refreshMusic(active());
setInterval(()=>{if(!document.hidden)refreshMusic(active());},15*60*1000);
